name: CI process at Pull request

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # 테스트용 MariaDB 컨테이너 추가
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    env:
      DATABASE_URL: jdbc:mariadb://localhost:3306/testdb
      DATABASE_USERNAME: testuser
      DATABASE_PASSWORD: testpass
      DATABASE_DRIVER: org.mariadb.jdbc.Driver
      JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      MAX_FILE_SIZE: ${{ secrets.MAX_FILE_SIZE }}
      MAX_REQUEST_SIZE : ${{ secrets.MAX_REQUEST_SIZE }}
      MINIO_ENDPOINT: ${{secrets.MINIO_ENDPOINT}}
      MINIO_ACCESS_KEY: ${{secrets.MINIO_ACCESS_KEY}}
      MINIO_SECRET_KEY: ${{secrets.MINIO_SECRET_KEY}}
      MINIO_BUCKET_NAME: ${{secrets.MINIO_BUCKET_NAME}}
      MINIO_PORTFOLIO_BUCKET_NAME: ${{secrets.MINIO_PORTFOLIO_BUCKET_NAME}}
      MINIO_PW: ${{secrets.MINIO_PW}}
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
      MINIO_ARCHIVE_THUMBNAIL: ${{secrets.MINIO_ARCHIVE_THUMBNAIL}}
      MINIO_ARCHIVE_IMG: ${{secrets.MINIO_ARCHIVE_IMG}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Cache Sonar and Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.sonar/cache
        key: ${{ runner.os }}-ci-${{ hashFiles('sequence_member/**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-ci

    - name: Build, Test, and SonarQube Analysis
      working-directory: sequence_member
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_USE_BUILD_TOOL_JDK: "true"
      run: ./gradlew build sonar --info

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        build-root-directory: sequence_member